// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    message_count,
    prompt_tokens,
    completion_tokens,
    cache_creation_tokens,
    cache_read_tokens,
    cache_miss_tokens,
    total_prompt_tokens,
    total_completion_tokens,
    total_reasoning_tokens,
    agent_name,
    model,
    provider,
    cost,
    summary_message_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, cache_creation_tokens, cache_read_tokens, cache_miss_tokens, total_prompt_tokens, total_completion_tokens, total_reasoning_tokens, agent_name, model, provider
`

type CreateSessionParams struct {
	ID                    string         `json:"id"`
	ParentSessionID       sql.NullString `json:"parent_session_id"`
	Title                 string         `json:"title"`
	MessageCount          int64          `json:"message_count"`
	PromptTokens          int64          `json:"prompt_tokens"`
	CompletionTokens      int64          `json:"completion_tokens"`
	CacheCreationTokens   int64          `json:"cache_creation_tokens"`
	CacheReadTokens       int64          `json:"cache_read_tokens"`
	CacheMissTokens       int64          `json:"cache_miss_tokens"`
	TotalPromptTokens     int64          `json:"total_prompt_tokens"`
	TotalCompletionTokens int64          `json:"total_completion_tokens"`
	TotalReasoningTokens  int64          `json:"total_reasoning_tokens"`
	AgentName             string         `json:"agent_name"`
	Model                 string         `json:"model"`
	Provider              string         `json:"provider"`
	Cost                  float64        `json:"cost"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CacheCreationTokens,
		arg.CacheReadTokens,
		arg.CacheMissTokens,
		arg.TotalPromptTokens,
		arg.TotalCompletionTokens,
		arg.TotalReasoningTokens,
		arg.AgentName,
		arg.Model,
		arg.Provider,
		arg.Cost,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.CacheMissTokens,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalReasoningTokens,
		&i.AgentName,
		&i.Model,
		&i.Provider,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const getLastSession = `-- name: GetLastSession :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, cache_creation_tokens, cache_read_tokens, cache_miss_tokens, total_prompt_tokens, total_completion_tokens, total_reasoning_tokens, agent_name, model, provider
FROM sessions
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLastSession(ctx context.Context) (Session, error) {
	row := q.queryRow(ctx, q.getLastSessionStmt, getLastSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.CacheMissTokens,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalReasoningTokens,
		&i.AgentName,
		&i.Model,
		&i.Provider,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, cache_creation_tokens, cache_read_tokens, cache_miss_tokens, total_prompt_tokens, total_completion_tokens, total_reasoning_tokens, agent_name, model, provider
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.CacheMissTokens,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalReasoningTokens,
		&i.AgentName,
		&i.Model,
		&i.Provider,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, cache_creation_tokens, cache_read_tokens, cache_miss_tokens, total_prompt_tokens, total_completion_tokens, total_reasoning_tokens, agent_name, model, provider
FROM sessions
WHERE parent_session_id is NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.CacheMissTokens,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalReasoningTokens,
			&i.AgentName,
			&i.Model,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSession = `-- name: RenameSession :exec
UPDATE sessions
SET
    title = ?
WHERE id = ?
`

type RenameSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) error {
	_, err := q.exec(ctx, q.renameSessionStmt, renameSession, arg.Title, arg.ID)
	return err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    cache_creation_tokens = ?,
    cache_read_tokens = ?,
    cache_miss_tokens = ?,
    total_prompt_tokens = ?,
    total_completion_tokens = ?,
    total_reasoning_tokens = ?,
    agent_name = ?,
    model = ?,
    provider = ?,
    summary_message_id = ?,
    cost = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, cache_creation_tokens, cache_read_tokens, cache_miss_tokens, total_prompt_tokens, total_completion_tokens, total_reasoning_tokens, agent_name, model, provider
`

type UpdateSessionParams struct {
	Title                 string         `json:"title"`
	PromptTokens          int64          `json:"prompt_tokens"`
	CompletionTokens      int64          `json:"completion_tokens"`
	CacheCreationTokens   int64          `json:"cache_creation_tokens"`
	CacheReadTokens       int64          `json:"cache_read_tokens"`
	CacheMissTokens       int64          `json:"cache_miss_tokens"`
	TotalPromptTokens     int64          `json:"total_prompt_tokens"`
	TotalCompletionTokens int64          `json:"total_completion_tokens"`
	TotalReasoningTokens  int64          `json:"total_reasoning_tokens"`
	AgentName             string         `json:"agent_name"`
	Model                 string         `json:"model"`
	Provider              string         `json:"provider"`
	SummaryMessageID      sql.NullString `json:"summary_message_id"`
	Cost                  float64        `json:"cost"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CacheCreationTokens,
		arg.CacheReadTokens,
		arg.CacheMissTokens,
		arg.TotalPromptTokens,
		arg.TotalCompletionTokens,
		arg.TotalReasoningTokens,
		arg.AgentName,
		arg.Model,
		arg.Provider,
		arg.SummaryMessageID,
		arg.Cost,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.CacheMissTokens,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalReasoningTokens,
		&i.AgentName,
		&i.Model,
		&i.Provider,
	)
	return i, err
}
